repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: name-tests-test
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E309,E501
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.7  # Keep this version in sync with flake8 in yesqa additional_dependencies
    hooks:
    -   id: flake8
        args:
        - --ignore=W503
        exclude: ^docs
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        args:
        - --add-import
        - from __future__ import absolute_import
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
    -   id: yesqa
        additional_dependencies:
        - flake8==3.7.7  # keep this in sync with flake8 pre-commit version
