sudo: false
language: python
matrix:
    include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "2.7"
      env: TOXENV=py27-pyramid15
    - python: "3.6"
      env: TOXENV=docs
    - env: TOXENV=mypy
      python: "3.6"
install: pip install tox coveralls
script: tox
after_success: coveralls
